# Generated by Django 4.1.2 on 2022-10-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photomodel',
            table='photo',
        ),
    ]
