# Generated by Django 4.1.2 on 2022-10-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='img',
        ),
        migrations.AddField(
            model_name='photomodel',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
