# Generated by Django 4.1.2 on 2022-10-21 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_remove_photomodel_favorites_favorit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trash',
            old_name='trash',
            new_name='trash_img',
        ),
    ]
