# Generated by Django 4.1.2 on 2022-10-19 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_rename_user_id_photomodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photomodel')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
